# Generated by Django 4.1.1 on 2022-09-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_alter_student_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
