# Generated by Django 4.1.2 on 2022-10-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=15)),
                ('operation_airlines', models.CharField(max_length=50)),
                ('departure_city', models.CharField(max_length=15)),
                ('arrival_city', models.CharField(max_length=15)),
                ('date_of_departure', models.DateField()),
                ('time_of_departure', models.TimeField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
